<?php

/**
 * @file
 * Manages ln_address module.
 */


/**
 * Implements hook_theme().
 */
function ln_address_theme($existing, $type, $theme, $path) {
  return [
    'site_address_block'  => [
      'template'  => 'block--address-block',
      'variables' => [
        'country'     => NULL,
        'city'        => NULL,
        'timezone'    => NULL,
        'time'        => NULL,
        'is_data'     => NULL,
      ],
    ],
  ];
}
